import { afterEach, describe, expect, it, vi } from "vitest";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { detectDsoIntent, registerTools } from "../src/tools.js";

/* ------------------------------------------------------------------ */
/*  The DSO route must not take questions that other routes answer.   */
/*  With DSO_API_KEY set, every question below gets the plan it gets  */
/*  without the key, which is the plan it had before the DSO route:   */
/*  the first review round's corpus, the second round's and a set of  */
/*  questions with DSO words, numbers, places and addresses.          */
/* ------------------------------------------------------------------ */

type Handler = (args: Record<string, unknown>) => Promise<{ content: Array<{ type: string; text: string }> }>;
const tools = new Map<string, { schema: Record<string, { parse: (v: unknown) => unknown }>; handler: Handler }>();
registerTools({
  registerTool(name: string, cfg: { inputSchema?: Record<string, { parse: (v: unknown) => unknown }> }, handler: Handler) {
    tools.set(name, { schema: cfg.inputSchema ?? {}, handler });
  },
} as unknown as McpServer);

async function plan(question: string): Promise<Record<string, unknown>> {
  const tool = tools.get("nl_gov_ask")!;
  const args: Record<string, unknown> = { question, dryRun: true, reference_now: "2026-10-06T10:00:00+02:00" };
  const parsed: Record<string, unknown> = {};
  for (const [key, schema] of Object.entries(tool.schema)) parsed[key] = schema.parse(args[key]);
  const out = await tool.handler(parsed);
  return JSON.parse(out.content[0].text);
}

/** Questions for the other routes, by the route they take. */
export const NON_DSO_QUESTIONS: Record<string, string[]> = {
  cbs: [
    "Hoeveel inwoners heeft Utrecht?",
    "Wat is de werkloosheid in Nederland?",
    "Hoe hoog was de inflatie in 2024?",
    "Hoeveel woningen zijn er in Amsterdam?",
    "Wat is het gemiddeld inkomen per gemeente?",
    "Hoeveel geboortes waren er vorig jaar?",
    "Wat is het opleidingsniveau in Rotterdam?",
    "Hoe groot is de bevolking van Den Haag?",
    "CBS cijfers over emissies van broeikasgassen",
    "Wat is de export van Nederland naar Duitsland?",
    "Statistiek over de economie van Utrecht",
  ],
  tweedeKamer: [
    "Welke moties zijn ingediend over stikstof?",
    "Welke amendementen zijn aangenomen op de begroting van Defensie?",
    "Kamervragen over de woningnood",
    "Welke wetsvoorstellen gaan over de Omgevingswet?",
    "Wat zei de commissie Infrastructuur over Schiphol?",
    "Hoe stemde de fractie van de VVD over het klimaatakkoord?",
    "Stemmingen in de Tweede Kamer over asiel",
    "Debatten over de Omgevingswet in de Tweede Kamer",
    "Welke Kamerstukken gaan over de invoering van de Omgevingswet?",
    "Wat vroeg het Kamerlid over windmolens?",
  ],
  bekendmakingen: [
    "Bekendmakingen over parkeren in Utrecht",
    "Staatsblad publicaties over de Omgevingswet",
    "Wat staat er in de Staatscourant over subsidies?",
    "Gemeenteblad Amsterdam verordening parkeerbelasting",
    "Officiële publicaties over de energietransitie",
    "Provinciaal blad Utrecht verkeersbesluit",
    "Waterschapsblad De Stichtse Rijnlanden",
  ],
  rechtspraak: [
    "Uitspraken over huurbescherming",
    "Rechtspraak over ontslag op staande voet",
    "Uitspraken van de Raad van State over windturbines",
    "Wat heeft de Hoge Raad gezegd over belastingrente?",
    "Arresten van het gerechtshof Den Haag over Shell",
    "Tuchtrecht uitspraken over artsen",
    "Jurisprudentie over de Omgevingswet",
    "Beroep tegen een besluit van de gemeente Utrecht",
    "Bezwaar tegen de WOZ-waarde",
    "Hoeveel boetes heeft de gemeente Utrecht opgelegd?",
    "Handhaving bij illegale bouw in Amsterdam",
    "Uitspraken van de Centrale Raad van Beroep over de WIA",
  ],
  knmi: [
    "Wat was de temperatuur in De Bilt gisteren?",
    "Hoeveel regen viel er vorige week?",
    "Was er een aardbeving in Groningen?",
    "Hoe hard waaide de wind tijdens de storm?",
  ],
  adressen: [
    "Wat is het bouwjaar van Brennerbaan 150 in Utrecht?",
    "Welke adressen zijn er op postcode 3524 BN?",
    "Hoeveel verblijfsobjecten heeft Utrecht?",
    "BAG gegevens van Damrak 1 Amsterdam",
    "Wat is de oppervlakte van het pand op Brennerbaan 150?",
    "Wat is de bestemming van het perceel Damrak 1 Amsterdam?",
  ],
  rdw: [
    "Hoeveel elektrische auto's zijn er geregistreerd?",
    "RDW gegevens van kenteken AB-123-C",
    "Welke voertuigen zijn er van het merk Tesla?",
  ],
  raad: [
    "Wat heeft de gemeenteraad van Utrecht besloten over parkeren?",
    "Wanneer besprak de raad van Utrecht de begroting?",
    "Wat vindt het college van Amersfoort van zonneparken?",
    "Welke raadsvoorstellen gaan over woningbouw in Delft?",
    "Wat zei de wethouder van Rotterdam over de haven?",
    "Raadsinformatiebrieven over jeugdzorg in Utrecht",
    "Wat hebben Gedeputeerde Staten van Gelderland besloten over windmolens?",
    "Welke programma's heeft Gedeputeerde Staten van Utrecht vastgesteld?",
    "Wat zei de burgemeester van Tilburg over drugsoverlast?",
    "Moties in de gemeenteraad van Groningen over de omgevingsvisie",
  ],
  tenders: [
    "Welke aanbestedingen zijn er voor ICT bij Rijkswaterstaat?",
    "TenderNed opdrachten voor schoonmaak",
    "Gunning van de opdracht voor de nieuwe brug in Utrecht",
    "Inkoop van software door de gemeente Amsterdam",
    "Marktconsultatie omgevingsplan gemeente Utrecht",
  ],
  algoritmes: [
    "Welke algoritmes gebruikt de gemeente Amsterdam?",
    "Algoritmeregister Belastingdienst",
    "Welke algoritmes gebruikt de gemeente Utrecht voor vergunningen?",
  ],
  apiRegister: [
    "Welke API heeft de overheid voor adressen?",
    "Is er een API voor omgevingsplannen?",
    "Welke API's zijn er voor het DSO?",
  ],
  begroting: [
    "Hoeveel geeft Nederland uit aan defensie?",
    "Wat is de begroting van het ministerie van Onderwijs?",
    "Rijksbegroting 2025 zorg",
    "Wat kost de invoering van de Omgevingswet?",
  ],
  rijksoverheid: [
    "Wat zegt het kabinet over de woningmarkt?",
    "Nieuws van de Rijksoverheid over de Omgevingswet",
    "Wanneer zijn de schoolvakanties in regio Noord?",
    "Toespraak van de minister-president over Europa",
    "Wat doet het ministerie van Infrastructuur aan files?",
  ],
  bestemmingsplannen: [
    "Welk bestemmingsplan geldt er voor Brennerbaan 150 in Utrecht?",
    "Welke vigerende bestemmingsplannen lopen er in Groningen?",
    "Toon het bestemmingsplan van Utrecht",
    "Bestemmingsplan buitengebied Ede",
    "Welke ruimtelijke plannen gelden er in Amersfoort?",
  ],
  vergunningen: [
    "Welke omgevingsvergunningen zijn er recent verleend in Utrecht?",
    "Omgevingsvergunning Brennerbaan 150 Utrecht",
    "Hoe vraag ik een omgevingsvergunning aan voor een dakkapel?",
    "Hoeveel omgevingsvergunningen verleende Amsterdam in 2025?",
    "Hoeveel vergunningen zijn verleend onder de Omgevingswet in Utrecht?",
    "Hoe lang duurt een vergunningprocedure onder de Omgevingswet in Amsterdam?",
    "Welke vergunningen heeft de gemeente Utrecht verleend voor terrassen?",
    "Evenementenvergunning aanvragen in Rotterdam",
  ],
  verordeningen: [
    "Verordening parkeren gemeente Utrecht",
    "Wat staat er in de APV van Amsterdam over vuurwerk?",
    "Afvalstoffenverordening Rotterdam",
    "Welke verordeningen heeft de gemeente Utrecht over hondenbelasting?",
    "verordening provincie Utrecht",
  ],
  wetten: [
    "Wat zegt artikel 5.1 van de Omgevingswet?",
    "Wanneer is de Omgevingswet in werking getreden?",
    "Wat zegt de Omgevingswet over Natura 2000?",
    "Wat is de Omgevingswet?",
    "Wat staat er in de Woningwet over huurprijzen?",
    "Wat zegt het Besluit bouwwerken leefomgeving over dakkapellen?",
    "Omgevingswet 2024 Nederland",
    "Wat regelt de Omgevingswet in Nederland?",
  ],
  eu: [
    "Wat is Verordening (EU) 2016/679?",
    "Hoe is richtlijn 2019/1024 in Nederland omgezet?",
    "Welke EU-richtlijnen gaan over luchtkwaliteit?",
    "Welk omgevingsprogramma heeft de EU?",
  ],
  energielabels: [
    "Welk energielabel heeft Brennerbaan 150 in Utrecht?",
    "Hoeveel woningen hebben energielabel A in Utrecht?",
    "EP-online energielabels Amsterdam",
  ],
  duo: [
    "Hoeveel leerlingen heeft de basisschool in Utrecht?",
    "Slagingspercentages van middelbare scholen in Amsterdam",
    "Welke scholen zijn er in Delft?",
    "Hoeveel studenten studeren aan de universiteit van Utrecht?",
  ],
  overig: [
    "Hoe is de luchtkwaliteit in Amsterdam?",
    "Fijnstof metingen in Utrecht",
    "Wat was de verkiezingsuitslag in Utrecht?",
    "Opkomst bij de gemeenteraadsverkiezingen in Rotterdam",
    "Welke gewaspercelen liggen in Ede?",
    "Welke gemeenten bieden een productbeschrijving voor parkeervergunningen?",
    "Welke datasets zijn er over luchtkwaliteit?",
    "Open data over verkeersongevallen",
    "Welke gegevens heeft de gemeente over parkeren?",
  ],
  beleid: [
    "Wat doet de Belastingdienst met de BTW?",
    "GGZ-beleid gemeente Utrecht",
    "Wat is het woonbeleid van de gemeente Amsterdam?",
    "Hoe gaat de gemeente Utrecht om met de Omgevingswet?",
    "Klachten over de Omgevingswet in gemeente Utrecht",
    "Hoeveel handhavingsverzoeken kreeg de gemeente Utrecht sinds de Omgevingswet?",
    "Hoeveel geeft het Rijk uit aan de invoering van de Omgevingswet in Utrecht?",
    "Wat kost de invoering van de Omgevingswet voor de gemeente Utrecht?",
    "Hoe verliep de Omgevingswet invoering 2024 in Utrecht?",
    "Wat is het klimaatbeleid van de provincie Utrecht?",
    "Omgevingswet invoering kosten gemeenten",
    "omgevingsdienst Utrecht handhaving",
    "Wat is de rol van de omgevingsdienst bij bodemsanering?",
    "Hoe staat het met de woningbouw in Utrecht?",
    "Welke maatregelen neemt de gemeente Den Haag tegen hittestress?",
    "Welke regels gelden op Koningsdag 2026 in Amsterdam?",
  ],
  // A DSO document word, but the question asks another source for it.
  dsoWoordAndereBron: [
    "Welke Kamervragen zijn gesteld over het omgevingsplan?",
    "Wanneer besprak de raad van Utrecht het omgevingsplan?",
    "Wat besloot de raad van Utrecht over het omgevingsplan?",
    "Wanneer vergadert de raad van Amersfoort over het omgevingsprogramma?",
    "Uitspraken van de Raad van State over omgevingsplannen",
    "Aanbestedingen voor een omgevingsvisie",
    "Hoeveel kost het omgevingsplan de gemeente?",
    "Welke tenders zijn er voor het opstellen van een omgevingsplan?",
    "Welke wetsvoorstellen gaan over het omgevingsplan?",
    "Wat zei de commissie Binnenlandse Zaken over de omgevingsvisie?",
    "Wat heeft de Hoge Raad gezegd over het omgevingsplan?",
    "Handhaving omgevingsplan Utrecht boete",
    "Officiële publicatie van het omgevingsplan van Utrecht",
    "Staatsblad publicatie omgevingsplan Rotterdam",
    "Welke API heeft de overheid voor omgevingsplannen?",
    "Begroting omgevingsvisie provincie Utrecht",
    "Welke gemeenten hebben al een omgevingsvisie vastgesteld volgens het CBS?",
    "Wat zegt de Rijksoverheid over voorbereidingsbesluiten?",
    "Wat zegt het kabinet over de omgevingsvisie?",
    "Welke datasets zijn er over omgevingsplannen?",
    "Wat vindt de raad van Amersfoort van de omgevingsvisie?",
    "Welke besluiten nam het college van Utrecht over het omgevingsplan?",
    "Welke fracties stemden tegen het omgevingsplan in de raad van Utrecht?",
    "Stemming over de omgevingsvisie in Provinciale Staten van Utrecht",
    "Provinciale Staten van Utrecht over de omgevingsverordening",
    "Hoe heeft de raad in Delft het omgevingsplan besproken?",
    "Is het omgevingsplan van Utrecht al door de raad vastgesteld?",
    "Nieuws over het omgevingsplan van Utrecht",
    "Persberichten over de omgevingsvisie",
    "Wat zei de minister van VRO over voorbereidingsbesluiten?",
    "Wat zei de staatssecretaris over het omgevingsplan?",
    "Subsidie voor het opstellen van een omgevingsprogramma",
    "Bezwaar tegen het voorbereidingsbesluit van Utrecht",
    "Is er beroep ingesteld tegen het omgevingsplan van Amsterdam?",
    "Moties over de omgevingsvisie in de Tweede Kamer",
    "Bekendmakingen over het omgevingsplan van Utrecht",
    "Gemeenteblad omgevingsplan Utrecht",
    "Welke omgevingsvergunningen zijn verleend op basis van het omgevingsplan van Utrecht?",
    "Welk bestemmingsplan is opgegaan in het omgevingsplan van Utrecht?",
    "Wat zegt de APV van Utrecht over het omgevingsplan?",
    "Welke ontwerpbesluiten liggen ter inzage in de gemeente Utrecht?",
    "Ontwerpbegroting provincie Utrecht ter inzage",
    "Welke ontwerp-verkeersbesluiten liggen ter inzage in de gemeente Utrecht?",
    "Tuchtrecht omgevingsplan architect",
    "Statistieken over omgevingsvisies van gemeenten",
    "Aanbesteding omgevingsplan Rotterdam",
    "Persbericht omgevingsvisie provincie Utrecht",
    "Toespraak over de omgevingsvisie",
    "Debat over het omgevingsplan in Amsterdam",
    "Rechterlijke uitspraak over een voorbereidingsbesluit",
    "Overtreding van het omgevingsplan in Utrecht",
    "Open data over omgevingsplannen",
    "Welke kosten maakt Amsterdam voor de omgevingsvisie?",
    "Hoeveel geld is er begroot voor het omgevingsprogramma geluid?",
  ],
};

/**
 * The second review round's corpus: every question it did not mark as a DSO
 * question, by its category ("grey" questions too; only "Hoeveel
 * omgevingsplannen zijn er in Nederland?" is in DSO_QUESTIONS, a list only the
 * DSO holds).
 */
const ROUND_TWO_NON_DSO: Record<string, string[]> = {
  cbs: [
    "Hoeveel inwoners had Zwolle op 1 januari 2025?",
    "Hoe ontwikkelt de werkloosheid onder jongeren zich sinds 2020?",
    "Wat was de inflatie in september 2026?",
    "Hoeveel woningen zijn er in 2025 opgeleverd in Almere?",
    "Gemiddeld besteedbaar inkomen per huishouden in Groningen",
    "Hoeveel sterfgevallen waren er in de winter van 2025?",
    "Wat is het bbp van Nederland in het tweede kwartaal?",
    "CBS cijfers over het aantal zzp'ers",
    "Hoeveel mensen wonen er in de wijk Lunetten in Utrecht?",
    "Wat is de bevolkingsgroei van Amersfoort sinds 2015?",
    "Hoeveel import van aardgas uit Noorwegen?",
    "Statistieken over de huizenprijzen in Rotterdam in 2024",
    "Wat is het opleidingsniveau van inwoners van Heerlen?",
    "Hoeveel emissies van CO2 had de industrie in 2023?",
    "Hoeveel geboortes waren er in Friesland vorig jaar?",
  ],
  tk: [
    "Welke moties over de woningbouwopgave zijn in 2025 aangenomen?",
    "Kamervragen over de Lelylijn",
    "Welke amendementen zijn ingediend bij de Wet betaalbare huur?",
    "Wat is de status van het wetsvoorstel over de Omgevingswet aanvullingsspoor geluid?",
    "Welke debatten waren er over stikstof in september?",
    "Hoe stemde de fractie van GroenLinks-PvdA over de asielnoodmaatregelenwet?",
    "Wat zei de commissie Volkshuisvesting over de Omgevingswet?",
    "Kamerstukken over de invoering van het Digitaal Stelsel Omgevingswet",
    "Welke Kamerleden stelden vragen over Tata Steel in IJmuiden?",
    "Stemmingen in de Tweede Kamer over de begroting van Defensie 2026",
    "Moties over het omgevingsplan van Amsterdam in de Tweede Kamer",
    "Welke kamervragen zijn gesteld over de storingen in het DSO?",
    "Wat zei de premier in het debat over de Voorjaarsnota?",
    "Parlementaire stukken over de nationale omgevingsvisie",
    "Welke wetsvoorstellen gaan over de huurtoeslag?",
  ],
  ob: [
    "Staatscourant publicaties over de regeling energieprestatie",
    "Gemeenteblad Utrecht parkeerverordening 2026",
    "Bekendmakingen van de gemeente Zwolle over kapvergunningen",
    "Provinciaal blad Gelderland omgevingsverordening",
    "Waterschapsblad Rijnland keur",
    "Officiële publicaties over het Besluit kwaliteit leefomgeving",
    "Staatsblad Omgevingswet inwerkingtreding",
    "Bekendmaking verkeersbesluit Kerkstraat 10 Haarlem",
    "Gemeenteblad Amsterdam omgevingsplan wijziging",
    "Welke bekendmakingen zijn er over Brennerbaan 150 in Utrecht?",
    "Staatscourant regeling subsidie verduurzaming woningen",
    "Welke regelingen heeft de gemeente Ede gepubliceerd?",
    "Officieel besluit over de tarieven van de afvalstoffenheffing in Rotterdam",
    "Bekendmakingen ter inzage in de gemeente Utrecht",
    "Tractatenblad verdrag met Duitsland",
  ],
  rechtspraak: [
    "Uitspraken over een omgevingsvergunning voor een dakkapel",
    "Wat heeft de Raad van State besloten over het omgevingsplan van Amsterdam?",
    "Rechtspraak over de Omgevingswet in 2025",
    "Jurisprudentie over het voorbereidingsbesluit van Utrecht",
    "Hoeveel zaken over huurverhoging heeft de rechtbank Amsterdam behandeld?",
    "Arresten van de Hoge Raad over de WOZ-waarde",
    "Vonnis in de zaak tegen Shell over CO2-uitstoot",
    "Beroep tegen het omgevingsplan van Rotterdam bij de Raad van State",
    "Bezwaar tegen het voorbereidingsbesluit van Haarlem",
    "ECLI uitspraken over geluidsoverlast van windturbines",
    "Uitspraken van het gerechtshof Arnhem-Leeuwarden over stikstof",
    "Handhaving van illegale bewoning op Oudegracht 245 in Utrecht",
    "Welke boetes zijn er uitgedeeld voor overtreding van de omgevingsverordening?",
    "Tuchtrecht uitspraken over notarissen",
    "Bestuursrecht uitspraken over de Wet open overheid",
  ],
  knmi: [
    "Hoe warm was het gisteren in Maastricht?",
    "Hoeveel regen viel er in augustus 2026 in De Bilt?",
    "Wat was de hoogste windsnelheid tijdens storm Ciarán?",
    "Was er gisteren een aardbeving bij Groningen?",
    "Wat is de temperatuur nu in Eindhoven?",
    "Hoe was het weer in Den Helder vorige week?",
    "Klimaat in Nederland: hoe warm was 2025?",
    "Weer op 1 januari 2025 in Utrecht",
  ],
  adres: [
    "Wat is het bouwjaar van Oudegracht 245 in Utrecht?",
    "Welke adressen liggen op postcode 1012 JS?",
    "BAG pand Kalverstraat 92 Amsterdam",
    "Wat is de gebruiksoppervlakte van Stationsplein 1 in Den Haag?",
    "Welk perceel hoort bij Dorpsstraat 1 in Ede?",
    "Hoeveel verblijfsobjecten staan er op Neude 11 in Utrecht?",
    "Wat is de gebruiksfunctie van het pand op Coolsingel 40 in Rotterdam?",
    "Kadastrale percelen rond Binnenhof 1 Den Haag",
    "Wat is de bestemming van Kerkplein 2 in Haarlem?",
    "Woonplaats bij postcode 3511 AB",
    "Hoe oud is het gebouw op Damrak 70 Amsterdam?",
    "Wat is de WOZ-waarde van Maliebaan 10 in Utrecht?",
  ],
  rdw: [
    "Hoeveel elektrische auto's zijn er in 2025 geregistreerd?",
    "RDW kentekengegevens van 12-ABC-3",
    "Hoeveel Volkswagens rijden er in Nederland?",
    "Wanneer moet een auto van 2015 naar de APK?",
    "Welke voertuigen hebben een terugroepactie?",
  ],
  raad: [
    "Wat heeft de gemeenteraad van Amersfoort besloten over het omgevingsplan?",
    "Raadsvoorstel omgevingsvisie Zwolle",
    "Wethouder van Utrecht over het omgevingsplan",
    "Wat zei de burgemeester van Rotterdam over het omgevingsplan?",
    "Raadsinformatiebrief omgevingsprogramma Utrecht",
    "Wanneer stelt de raad van Haarlem de omgevingsvisie vast?",
    "Welke moties over het omgevingsplan zijn aangenomen in de raad van Delft?",
    "Collegebesluit voorbereidingsbesluit Utrecht",
    "Raadsvergadering Leiden over het omgevingsplan",
    "Wat besloot het college van Arnhem over zonneparken?",
    "Raadsbesluit omgevingsvisie Arnhem 2040",
    "Wat bespreekt de gemeenteraad van Utrecht volgende week?",
    "Agenda raadsvergadering Goeree-Overflakkee",
    "Wat vindt de raad van Zwijndrecht van de omgevingsvisie?",
    "Hoe stemde de raad in Zwolle over het omgevingsplan?",
  ],
  staten: [
    "Wat besloten Provinciale Staten van Utrecht over de omgevingsverordening?",
    "Gedeputeerde Staten van Gelderland over windmolens",
    "Statenvoorstel omgevingsverordening Noord-Holland",
    "Statenleden over de omgevingsvisie van Drenthe",
    "Provinciale Staten Zuid-Holland omgevingsvisie vaststelling",
    "Wat zei Gedeputeerde Staten van Fryslân over het omgevingsprogramma?",
    "Statenvergadering over de omgevingsverordening van Overijssel",
    "Statenbrief omgevingsverordening Utrecht",
  ],
  tenders: [
    "Aanbestedingen voor het opstellen van een omgevingsplan in Gelderland",
    "Welke tenders heeft Rijkswaterstaat uitgeschreven voor bruggen?",
    "Gunning opdracht DSO-aansluiting gemeente Utrecht",
    "Marktconsultatie omgevingsvisie provincie Utrecht",
    "Inkoop van software voor het Omgevingsloket",
    "TenderNed opdrachten groenonderhoud Amersfoort",
    "Welke overheidsopdrachten zijn er voor ICT bij Defensie?",
    "Europese aanbesteding omgevingsdienst",
  ],
  algoritme: [
    "Welke algoritmes gebruikt de gemeente Rotterdam voor bijstand?",
    "Algoritmeregister Dienst Toeslagen",
    "Algoritmes voor vergunningverlening in Utrecht",
    "Welke algoritmes gebruikt het UWV?",
    "Algoritmeregister omgevingsdienst",
  ],
  api: [
    "Welke API heeft de overheid voor bekendmakingen?",
    "Is er een API voor het Omgevingsloket?",
    "Welke API's biedt het Kadaster?",
    "Is er een API voor omgevingsdocumenten?",
    "Welke API heeft het DSO voor regels op de kaart?",
  ],
  begroting: [
    "Hoeveel geeft het Rijk uit aan de Omgevingswet?",
    "Wat is de begroting van het ministerie van VRO in 2026?",
    "Rijksbegroting 2026 defensie-uitgaven",
    "Budget voor het Digitaal Stelsel Omgevingswet",
    "Wat kost het DSO per jaar?",
    "Hoeveel geld gaat naar woningbouw in 2025?",
    "Uitgaven aan jeugdzorg per gemeente",
    "Begroting provincie Utrecht omgevingsvisie 2026",
  ],
  rijk: [
    "Wat zegt het kabinet over de invoering van de Omgevingswet?",
    "Persbericht van het ministerie van BZK over het DSO",
    "Wat doet het ministerie van LVVN aan stikstof?",
    "Nieuws over de Omgevingswet van de Rijksoverheid",
    "Wat heeft de minister van VRO gezegd over omgevingsplannen?",
    "Toespraak van de koning op Prinsjesdag 2026",
    "Wanneer is de herfstvakantie in regio zuid?",
    "Wat is het beleid van het ministerie van IenW over Schiphol?",
    "Wat zegt de staatssecretaris over het omgevingsplan?",
    "Rijksoverheid nieuws over de Nationale Omgevingsvisie",
    "Ministerie van Defensie en de Omgevingswet",
    "Wat doet het kabinet aan de woningnood in Utrecht?",
  ],
  bestemmingsplan: [
    "Welk bestemmingsplan geldt op Oudegracht 245 in Utrecht?",
    "Bestemmingsplan Binnenstad Amersfoort",
    "Welke bestemmingsplannen liggen ter inzage in Ede?",
    "Bestemmingsplan buitengebied Goeree-Overflakkee",
    "Is het bestemmingsplan van Zwolle al vervangen door het omgevingsplan?",
    "Ruimtelijke plannen bij Damrak 1 Amsterdam",
    "Welk bestemmingsplan gold in 2023 voor Kerkstraat 10 in Haarlem?",
    "Wijzigingsplan bestemmingsplan Utrecht Leidsche Rijn",
    "Bestemmingsplannen in de provincie Utrecht",
    "Ontwerp-bestemmingsplan ter inzage in Arnhem",
  ],
  vergunning: [
    "Omgevingsvergunning voor een dakkapel in Utrecht aanvragen",
    "Welke omgevingsvergunningen zijn verleend op Oudegracht 245?",
    "Vergunningaanvraag voor een uitrit in Amersfoort",
    "Hoe lang duurt de vergunningverlening onder de Omgevingswet?",
    "Omgevingsvergunning bouwactiviteit Kalverstraat 1 Amsterdam",
    "Hoeveel omgevingsvergunningen verleende Rotterdam in 2025?",
    "Welke vergunningen zijn nodig voor een evenement in Utrecht?",
    "Kapvergunning aanvragen in Den Haag",
    "Terrasvergunning Neude Utrecht",
    "Welke vergunningsprocedures gelden onder de Omgevingswet in Utrecht?",
  ],
  verordening: [
    "Verordening hondenbelasting gemeente Ede",
    "APV Utrecht regels over vuurwerk",
    "Welke verordeningen heeft de gemeente Zwolle over parkeren?",
    "Huisvestingsverordening Amsterdam",
    "Afvalstoffenverordening Utrecht 2025",
    "Legesverordening Rotterdam 2026",
    "Verordening provincie Gelderland subsidies",
    "Algemene plaatselijke verordening Arnhem over terrassen",
  ],
  wetten: [
    "Wat zegt artikel 2.4 van de Omgevingswet?",
    "Wanneer trad de Omgevingswet in werking?",
    "Wat staat er in de Omgevingswet over het omgevingsplan?",
    "Welke artikelen van de Omgevingswet gaan over de omgevingsvisie?",
    "Wat regelt afdeling 16.3 van de Omgevingswet over participatie?",
    "Wat staat in het Besluit bouwwerken leefomgeving over vergunningvrij bouwen?",
    "Wat zegt de Woningwet over woningcorporaties?",
    "Wat is de Wet kwaliteitsborging voor het bouwen?",
    "Wat zegt de Omgevingswet over de zorgplicht?",
    "Wet open overheid artikel 3.3",
    "Wat staat er in de Gemeentewet over de burgemeester?",
    "Wat zegt de Omgevingswet over het projectbesluit?",
    "Hoe regelt de Omgevingswet de omgevingsvisie?",
    "Welke AMvB's horen bij de Omgevingswet?",
    "Wat zegt de Invoeringswet Omgevingswet over het overgangsrecht?",
  ],
  eu: [
    "Wat regelt Verordening (EU) 2024/1689 over AI?",
    "Hoe is de Kaderrichtlijn Water in Nederland omgezet?",
    "Welke EU-richtlijnen gaan over energieprestatie van gebouwen?",
    "Richtlijn 2011/92/EU milieueffectbeoordeling",
    "Europese regels voor natuurherstel",
    "CELEX 32016R0679",
    "Welke EU-verordening gaat over ontbossing?",
    "Wat is de Europese Habitatrichtlijn?",
  ],
  energielabel: [
    "Welk energielabel heeft Oudegracht 245 in Utrecht?",
    "Energielabel van Kerkstraat 10 Haarlem",
    "Hoeveel woningen in Amersfoort hebben label C of slechter?",
    "EP-online energielabel postcode 3511 AB 12",
    "Wat is het energielabel van het kantoor op Coolsingel 40 Rotterdam?",
    "Energielabels van scholen in Utrecht",
  ],
  duo: [
    "Hoeveel leerlingen zitten op basisscholen in Zwolle?",
    "Slagingspercentage havo in Amersfoort 2025",
    "Welke middelbare scholen zijn er in Arnhem?",
    "Hoeveel studenten studeren aan de TU Delft?",
    "Hoeveel mbo-studenten zijn er in Utrecht?",
    "Examenresultaten van het vwo in Groningen",
    "Basisschool op Kerkstraat 5 in Ede",
    "Hoeveel leraren werken er in het voortgezet onderwijs?",
  ],
  lucht: [
    "Hoe is de luchtkwaliteit op de Erasmusweg in Den Haag?",
    "Fijnstof in Amsterdam vandaag",
    "NO2 metingen bij Schiphol",
    "Luchtvervuiling in Rotterdam vorige week",
    "Smog in Nederland deze week",
  ],
  verkiezingen: [
    "Verkiezingsuitslag Tweede Kamerverkiezing 2025 in Utrecht",
    "Opkomst gemeenteraadsverkiezingen 2026 Rotterdam",
    "Uitslag Provinciale Statenverkiezingen 2023 Gelderland",
    "Hoeveel stemmen kreeg de VVD in Amersfoort?",
  ],
  gewas: [
    "Welke gewassen worden geteeld in de Noordoostpolder?",
    "Gewaspercelen rond Dronten",
    "Landbouwgrond in de gemeente Ede",
  ],
  catalogi: [
    "Welke gemeenten bieden een productbeschrijving voor een omgevingsvergunning?",
    "Loket voor afvalpas in Zwolle",
    "Productbeschrijvingen gemeente Utrecht parkeervergunning",
  ],
  datasets: [
    "Welke datasets zijn er over geluidsbelasting?",
    "Open data over bomen in Amsterdam",
    "Datasets over omgevingsplannen",
    "Data over verkeersintensiteit op de A12",
    "Welke databestanden zijn er over grondwaterstanden?",
    "Open data van de gemeente Utrecht",
  ],
  beleid: [
    "Wat is het woningbouwbeleid van de gemeente Zwolle?",
    "Hoe gaat de gemeente Amersfoort om met de Omgevingswet?",
    "Klimaatbeleid provincie Gelderland",
    "Wat doet de gemeente Utrecht aan participatie onder de Omgevingswet?",
    "Hoe staat het met de energietransitie in Arnhem?",
    "Hittestress beleid gemeente Rotterdam",
    "Hoe pakt de gemeente Den Haag de woningnood aan?",
    "Wat doet de omgevingsdienst Midden-Nederland?",
    "Wat is het mobiliteitsbeleid van Utrecht?",
    "Wat doet de Belastingdienst met de Omgevingswet?",
    "Hoe ervaren gemeenten de Omgevingswet?",
    "Wat is de rol van het waterschap bij de Omgevingswet?",
  ],
  politie: [
    "Hoeveel woninginbraken waren er in Utrecht in 2025?",
    "Criminaliteit in de wijk Kanaleneiland",
    "Geregistreerde misdrijven per gemeente 2024",
    "Hoeveel fietsdiefstallen in Amsterdam?",
    "Politiecijfers over drugsdelicten in Tilburg",
    "Misdrijven rond Damrak 1 Amsterdam",
  ],
  ongevallen: [
    "Verkeersongevallen op de A2 bij Utrecht in 2024",
    "Hoeveel verkeersdoden vielen er in 2025?",
    "Ongevallen met fietsers in Groningen",
  ],
  ov: [
    "Vertrektijden treinen Utrecht Centraal",
    "Storingen op het spoor tussen Amsterdam en Utrecht",
    "Wanneer gaat de bus van Neude naar Utrecht Centraal?",
    "NS reisinformatie Den Haag Centraal",
  ],
  water: [
    "Waterstand van de Rijn bij Lobith",
    "Wat is de waterhoogte in Rotterdam?",
    "Watertemperatuur in de Noordzee bij Scheveningen",
    "Rijkswaterstaat metingen Maas Venlo",
  ],
  bodem: [
    "Bodemopbouw onder Utrecht volgens BRO",
    "Grondwaterstanden in de Veluwe",
    "Sonderingen bij Brennerbaan 150 Utrecht",
  ],
  zorg: [
    "Wachttijden in de ggz in Utrecht",
    "Hoeveel ziekenhuizen zijn er in Gelderland?",
    "Zorgkosten per inwoner",
    "Vaccinatiegraad in Urk",
  ],
  dnb: [
    "Rente op spaarrekeningen volgens DNB",
    "DNB statistieken hypotheken 2025",
    "Hoeveel pensioenfondsen zijn er?",
  ],
  rivm: [
    "RIVM cijfers over griep",
    "Geluidsbelasting rond Schiphol volgens het RIVM",
    "Stikstofdepositie op de Veluwe",
  ],
  organisaties: [
    "Wat doet de Omgevingsdienst Haaglanden?",
    "Contactgegevens van het Hoogheemraadschap van Rijnland",
    "Welke ministeries zijn er?",
    "Wie is de secretaris-generaal van BZK?",
  ],
  eurostat: [
    "Eurostat werkloosheid in de eurozone",
    "Vergelijk de inflatie van Nederland met Duitsland",
  ],
  tricky: [
    "Sinds wanneer geldt de Omgevingswet in Amsterdam?",
    "Geldt de Omgevingswet ook op Bonaire?",
    "Welke leges gelden onder de Omgevingswet in Rotterdam?",
    "Hoe regelt de gemeente Utrecht participatie onder de Omgevingswet?",
    "Welke regels gelden op Koningsdag 27 april in Amsterdam?",
    "Welke regels gelden op Tweede Kerstdag 26 december voor winkels?",
    "Welke regels gelden voor vuurwerk in Amsterdam 31 december?",
    "Welke regels gelden voor een windpark van 1000 MW op zee?",
    "Welke regels gelden voor opslag van 1000 KG vuurwerk?",
    "Welke regels gelden voor Box 3 in Nederland?",
    "Welke regels gelden in de milieuzone voor Euro 6 in Utrecht?",
    "Welke regels gelden voor de huurprijs van Damrak 1 in Amsterdam?",
    "Welke regels gelden voor energielabels op Oudegracht 245 in Utrecht?",
    "Welke regels gelden voor afvalinzameling op Kerkstraat 10 in Haarlem?",
    "Welke regels gelden voor Airbnb op Kalverstraat 92 in Amsterdam?",
    "Welke regels gelden in de haven 24 uur per dag?",
    "Welke regels gelden voor drones bij Schiphol?",
    "Welke regels gelden voor honden in het Vondelpark?",
    "Wat is een omgevingsplan?",
    "Wie stelt het omgevingsplan vast?",
    "Wat is het verschil tussen een omgevingsvisie en een omgevingsprogramma?",
    "Hoe werkt een voorbereidingsbesluit?",
    "Wanneer moeten gemeenten hun omgevingsplan af hebben?",
    "Welke overgangsregels gelden onder de Omgevingswet voor lopende aanvragen in Groningen?",
    "Mag ik onder de Omgevingswet bezwaar maken in Utrecht?",
    "Hoe vraag ik onder de Omgevingswet een melding aan voor Damrak 1 in Amsterdam?",
    "Gelden de regels van de Omgevingswet ook voor Defensieterreinen in Ede?",
    "Wat verandert er met de Omgevingswet voor inwoners van Zwolle?",
    "Hoe regelt de provincie Gelderland de Omgevingswet?",
    "Inspraakavond omgevingsvisie Zwolle",
    "Ligt het ontwerp van de nieuwe brug in Utrecht ter inzage?",
    "Welke ontwerpen voor speeltuinen in Amsterdam liggen ter inzage?",
    "Hoeveel mensen werken bij de omgevingsdienst in Utrecht?",
    "Wat is de WOZ-waarde van woningen aan de Oudegracht 245 volgens de regels?",
    "Welke regels gelden voor parkeren op het Malieveld 1 in Den Haag?",
    "Welke regels gelden er voor terrassen op Neude 11 in Utrecht?",
    "Welke regels gelden voor evenementen in Utrecht onder de Omgevingswet?",
    "Welke regels gelden voor kamerverhuur op postcode 3511 AB?",
    "Welke regels gelden op 1 januari 2027 voor de huurtoeslag?",
    "Welke regels gelden voor de zondagsrust in Staphorst?",
    "Mag ik onder de Omgevingswet in Amsterdam een boom kappen?",
    "Welke regels gelden er onder de Omgevingswet voor schoolgebouwen in Delft?",
    "Wat zijn de regels voor energielabel C voor kantoren in 2023?",
    "Welke regels gelden voor de A2 tussen Utrecht en Amsterdam?",
    "Welke regels gelden er voor de Ring 10 rond Amsterdam?",
    "Welke regels gelden voor Groep 8 in Utrecht?",
    "Welke subsidieregels gelden op Brennerbaan 150 in Utrecht?",
    "Hoeveel inwoners heeft de gemeente met het omgevingsplan van Utrecht?",
    "Statenbrief over het ontwerp ter inzage van de provincie Utrecht",
    "Welke zienswijzen zijn ingediend op het ontwerp van de A27 bij Utrecht?",
    "Welke regels gelden voor bodemsanering op Kanaalweg 1 in Utrecht?",
    "Geldt de Omgevingswet ook voor de Waddenzee?",
    "Omgevingswet Den Haag regels",
    "Wat zegt de Omgevingswet over de regels in Amsterdam?",
  ],
  falseAddress: [
    "Welke regels gelden op Bevrijdingsdag 5 mei voor horeca?",
    "Welke regels gelden op Hemelvaartsdag 14 mei voor winkels?",
    "Welke regels gelden op Koopzondag 12 oktober in Utrecht?",
    "Welke regels gelden op Prinsjesdag 15 september in Den Haag?",
    "Welke regels gelden op Sinterklaas 5 december voor schoolkinderen?",
    "Welke regels gelden bij Windkracht 10 voor evenementen?",
    "Welke regels gelden voor Formule 1 in Zandvoort?",
    "Welke regels gelden voor Covid 19 in Utrecht?",
    "Welke regels gelden voor Categorie 3 in Rotterdam?",
    "Welke regels gelden voor Groep 7 in Zwolle?",
    "Welke regels gelden voor aanhangers boven 3500 KG?",
    "Welke regels gelden voor een warmtepomp van 1500 KW?",
    "Welke regels gelden voor herdenkingen op de Dam 4 mei?",
    "Welke regels gelden voor parkeren in de straat 2 uur lang?",
    "Welke regels gelden voor parkeren in Zaandam 2 uur gratis?",
    "Welke regels gelden voor verkiezingsborden in Rotterdam 2 weken voor de verkiezingen?",
    "Welke regels gelden op Schiphol Terminal 3 voor bagage?",
    "Welke regels gelden voor Rijksmonument 12345 in Utrecht?",
    "Welke regels gelden voor de inzet van Sectie 8 in Den Haag?",
  ],
  omgevingswetLawPolicy: [
    "Hoe regelt de gemeente Ede de Omgevingswet?",
    "Wat regelt de Omgevingswet in Limburg?",
    "Geldt de Omgevingswet in Zwolle ook voor bestaande bouw?",
    "Gelden de regels van de Omgevingswet al in Amsterdam?",
    "Hoe gaat de gemeente Den Bosch om met regels onder de Omgevingswet?",
    "Welke regels gelden onder de Omgevingswet voor participatie in Utrecht?",
    "Mag ik onder de Omgevingswet in Utrecht zelf een vergunningcheck doen?",
    "Is de Omgevingswet van toepassing in Caribisch Nederland?",
    "Wat zijn de regels voor ambtenaren in Utrecht sinds de Omgevingswet?",
  ],
  documentWordOtherSource: [
    "Parlementaire behandeling van de omgevingsvisie",
    "Kamerbrief over de voortgang van omgevingsplannen",
    "Kamerdebat over het omgevingsplan",
    "Statenvragen over de omgevingsverordening van Utrecht",
    "Raadsvragen over het omgevingsplan van Utrecht",
    "Persconferentie over de omgevingsvisie",
    "Woo-verzoek over het omgevingsplan van Utrecht",
    "Rekenkamerrapport over de omgevingsvisie van Amersfoort",
    "Klacht bij de Nationale ombudsman over het omgevingsplan",
    "Nota van zienswijzen ontwerp omgevingsvisie Amersfoort",
    "PS van Utrecht over de omgevingsverordening",
    "GS Gelderland besluit omgevingsverordening",
    "Wat zei de gedeputeerde over de omgevingsverordening?",
    "College van GS over de omgevingsverordening van Utrecht",
    "Dagelijks bestuur waterschap Rivierenland over de waterschapsverordening",
    "Algemeen bestuur Hoogheemraadschap van Rijnland stelt waterschapsverordening vast",
    "Wat besloot de Raad van Amersfoort over het omgevingsplan?",
    "Hoe denken de raadsfracties in Utrecht over het omgevingsplan?",
    "Commissievergadering omgevingsplan Utrecht",
    "Wat zegt BZK over de omgevingsvisie?",
    "Wat zegt de VNG over het omgevingsplan?",
    "Wat vindt het IPO van de omgevingsverordening?",
    "Hoeveel heeft het omgevingsplan van Utrecht gekost?",
    "Hoeveel investeert Utrecht in het omgevingsplan?",
    "Financiering omgevingsvisie Gelderland",
    "Evaluatie van de omgevingsvisie van Gelderland",
    "Inspraak omgevingsvisie Utrecht",
    "Wat vinden inwoners van het omgevingsplan van Utrecht?",
    "Planning omgevingsplan Rotterdam 2032",
    "Hoeveel mensen hebben een zienswijze ingediend op het ontwerp omgevingsplan van Utrecht?",
    "Reactienota zienswijzen omgevingsverordening Utrecht",
    "Vacature adviseur omgevingsplan gemeente Utrecht",
  ],
  ontwerpTerInzage: [
    "Ontwerp jaarrekening waterschap Rivierenland ter inzage",
    "Ontwerp kadernota gemeente Ede ter inzage",
    "Ontwerp aanwijzingsbesluit Natura 2000 ter inzage in Gelderland",
    "Ontwerp peilbesluit waterschap Vallei en Veluwe ter inzage",
    "Welk ontwerp ligt ter inzage voor de nieuwe sporthal in Zwolle?",
    "Ontwerp verkeersplan Utrecht ter inzage",
    "Ligt het ontwerp-tracébesluit A27 ter inzage?",
  ],
  lawDocumentWord: [
    "Wat zegt artikel 2.4 Omgevingswet over het omgevingsplan?",
    "Moet elke gemeente een omgevingsvisie hebben volgens de wet?",
    "Wat is de juridische status van een omgevingsvisie?",
    "Is een omgevingsvisie bindend voor burgers?",
    "Welke instructieregels uit het Bkl gelden voor het omgevingsplan?",
    "Wat staat er in het Omgevingsbesluit over het projectbesluit?",
  ],
  plainNonDso: [
    "Welke regels gelden voor thuiswerken bij het Rijk?",
    "Welke regels gelden voor de WOZ-waarde in 2026?",
    "Welke regels gelden voor kinderopvang in Utrecht?",
    "Welke regels gelden voor hondenpoep in Amersfoort?",
    "Welke regels gelden er in Utrecht voor deelscooters?",
    "Welke regels gelden er voor de bijstand in Rotterdam?",
    "Welke regelingen heeft de gemeente Zwolle voor minima?",
    "Mag ik in Utrecht mijn auto op de stoep parkeren?",
    "Wat zijn de openingstijden van het stadhuis van Utrecht?",
    "Welk waterschap hoort bij Brennerbaan 150 in Utrecht?",
    "In welke gemeente ligt postcode 3524 BN?",
    "Wat is de bouwhoogte van het pand op Brennerbaan 150?",
    "Hoeveel bomen staan er op de Maliebaan in Utrecht?",
    "Wat is de grondprijs in de provincie Utrecht?",
    "Welke monumenten staan er in de provincie Utrecht?",
    "Wat zijn de regels voor zonnepanelen op een monument volgens de Rijksdienst voor het Cultureel Erfgoed?",
  ],
};

/** Questions for other routes that carry DSO words, numbers, places and addresses. */
const ADVERSARIAL_NON_DSO: string[] = [
  "Wat is de WOZ-waarde van Kerkstraat 10 in Haarlem?",
  "Welke bedrijven zijn gevestigd op Brennerbaan 150 in Utrecht?",
  "Hoeveel mensen wonen er op Oudegracht 245 in Utrecht?",
  "Welk energielabel heeft het pand op Stationsplein 1 in Amersfoort?",
  "Wanneer is het pand op Kerkstraat 10 in Haarlem gebouwd?",
  "Welke regels gelden voor afval op Kerkstraat 10 in Haarlem?",
  "Welke regels gelden voor de huurprijs van Oudegracht 245 in Utrecht?",
  "Welke regels gelden voor parkeren op de Coolsingel 40 in Rotterdam?",
  "Welke regels gelden voor terrassen op het Stationsplein 1 in Amersfoort?",
  "Welke regels gelden voor evenementen op het Museumplein 1 in Amsterdam?",
  "Welke regels gelden voor honden op de Grote Markt 1 in Groningen?",
  "Welke regels gelden voor vuurwerk op de Dam 1 in Amsterdam op oudejaarsavond?",
  "Welke subsidie krijg ik voor zonnepanelen op Kerkstraat 10 in Ede?",
  "Welke regels gelden voor kamerverhuur op Oudegracht 245 in Utrecht?",
  "Welke regels gelden voor Airbnb op Prinsengracht 263 in Amsterdam?",
  "Bekendmaking verkeersbesluit Hoofdweg 10 Amsterdam",
  "Welke omgevingsvergunning is verleend voor Kanaalweg 1 in Utrecht?",
  "Handhavingsverzoek over Dorpsstraat 5 in Ede",
  "Welke regels gelden op Koningsdag 27 april op de Dam in Amsterdam?",
  "Welke regels gelden op Bevrijdingsdag 5 mei in Wageningen?",
  "Welke regels gelden tijdens Sail 2025 in Amsterdam?",
  "Welke regels gelden voor Formule 1 op Circuit Zandvoort?",
  "Welke regels gelden voor Fase 2 van de A27 bij Utrecht?",
  "Welke regels gelden voor Groep 8 bij de eindtoets in Zwolle?",
  "Welke regels gelden voor Box 3 in de inkomstenbelasting?",
  "Welke regels gelden in de milieuzone voor Euro 5 in Rotterdam?",
  "Welke regels gelden voor het Ring 10 project in Amsterdam?",
  "Welke regels gelden voor Windkracht 9 op de Waddenzee?",
  "Welke regels gelden voor een windpark van 700 MW op de Noordzee?",
  "Welke regels gelden voor aanhangers van 2500 KG?",
  "Wat kost een parkeervergunning voor Kerkstraat 10 in Haarlem?",
  "Welke regels gelden voor drones boven 120 meter in Utrecht?",
  "Welke regels gelden in Zaandam 3 dagen voor Koningsdag?",
  "Welke regels gelden in Rotterdam 2 weken na de storm?",
  "Welke regels gelden voor parkeren in de straat 3 uur lang?",
  "Welke moties over het omgevingsplan zijn aangenomen in de raad van Ede?",
  "Raadsvoorstel vaststelling omgevingsplan Amersfoort",
  "Wat vindt de wethouder van Zwolle van de omgevingsvisie?",
  "Statenvoorstel omgevingsvisie Gelderland 2050",
  "Wanneer stemt Provinciale Staten over de omgevingsverordening?",
  "Kamerbrief over de voortgang van de omgevingsvisies",
  "Wat zei de minister over het omgevingsplan van Utrecht?",
  "Persbericht over het voorbereidingsbesluit van Rotterdam",
  "Nieuwsbericht omgevingsvisie Den Haag",
  "Uitspraak van de Raad van State over het projectbesluit van de A27",
  "Beroep tegen het voorbereidingsbesluit van Amsterdam",
  "Bezwaarschrift tegen het omgevingsplan van Ede",
  "Aanbesteding opstellen omgevingsprogramma Utrecht",
  "Hoeveel kost het omgevingsplan van Rotterdam?",
  "Subsidieregeling voor het omgevingsprogramma van Gelderland",
  "Begroting voor de omgevingsvisie van Zwolle 2026",
  "Welke datasets bevatten omgevingsplannen van gemeenten?",
  "Is er een API voor de omgevingsvisies van provincies?",
  "Welke vacatures zijn er voor een adviseur omgevingsvisie in Utrecht?",
  "Evaluatie van de omgevingsverordening van Noord-Brabant",
  "Rekenkameronderzoek naar het omgevingsprogramma van Amersfoort",
  "Woo-besluit over het voorbereidingsbesluit van Haarlem",
  "Wat vinden bewoners van het omgevingsplan van Utrecht?",
  "Hoe denken ondernemers over het omgevingsplan van Ede?",
  "Commissie Ruimte bespreekt de omgevingsvisie van Utrecht",
  "Agenda gemeenteraad Zwolle omgevingsplan",
  "Inspraakreactie op de omgevingsvisie van Amersfoort",
  "Participatieverslag omgevingsplan Arnhem",
  "Informatieavond over het omgevingsplan in Ede",
  "Webinar over voorbereidingsbesluiten",
  "Hoe vraag ik een projectbesluit aan?",
  "Wat staat er in de Omgevingswet over het projectbesluit?",
  "Sinds wanneer geldt de Omgevingswet in Groningen?",
  "Welke leges gelden onder de Omgevingswet in Zwolle?",
  "Hoe regelt de gemeente Amersfoort participatie onder de Omgevingswet?",
  "Wat regelt de Omgevingswet in Drenthe?",
  "Gelden de regels van de Omgevingswet al in Den Haag?",
  "Welke regels gelden onder de Omgevingswet voor participatie in Zwolle?",
  "Welke overgangsregels gelden onder de Omgevingswet in Ede?",
  "Wat zegt de Omgevingswet over de regels in Rotterdam?",
  "Wat verandert de Omgevingswet voor bewoners van Delft?",
  "Wat is het verschil tussen een omgevingsplan en een bestemmingsplan?",
  "Wat betekent een voorbereidingsbesluit voor mijn huis?",
  "Wie stelt de omgevingsverordening vast?",
  "Moet een waterschap een waterschapsverordening hebben?",
  "Is een omgevingsprogramma verplicht voor gemeenten?",
  "Welke artikelen van het Bkl gaan over omgevingsplannen?",
  "Wat staat in het Bbl over vergunningvrije dakkapellen?",
  "Wat zegt de Invoeringswet over het omgevingsplan?",
  "Wanneer moeten provincies hun omgevingsverordening aanpassen?",
  "Waarom heeft Utrecht een voorbereidingsbesluit genomen?",
  "Wat is de juridische betekenis van een omgevingsvisie?",
  "Hoe werkt de bruidsschat in het omgevingsplan?",
  "What is an omgevingsplan?",
  "Who adopts the omgevingsvisie of a province?",
  "Ontwerpbegroting 2027 gemeente Zwolle ter inzage",
  "Ontwerp-jaarrekening provincie Gelderland ter inzage",
  "Welke ontwerp-bestemmingsplannen liggen ter inzage in Ede?",
  "Ontwerp peilbesluit Hoogheemraadschap van Rijnland ter inzage",
  "Ligt het ontwerp van het nieuwe stadhuis in Utrecht ter inzage?",
  "Welke ontwerpen voor de nieuwe brug in Arnhem liggen ter inzage?",
  "Ontwerp-verkeersbesluit Kerkstraat Haarlem ter inzage",
  "Ontwerpbesluit omgevingsvergunning ter inzage in de gemeente Ede",
  "Welke ontwerpen liggen ter inzage voor het nieuwe zwembad in Zwolle?",
  "Ontwerp kadernota waterschap Vallei en Veluwe ter inzage",
  "Welke adressen horen bij postcode 3511 AB?",
  "Hoeveel woningen staan er in postcode 1012 JS?",
  "In welke gemeente ligt 2011 ZR?",
  "Welke regels gelden voor een vrachtwagen van 3500 KG?",
  "Welke regels gelden voor een batterij van 500 KW in de wijk?",
  "Wat is de luchtkwaliteit bij postcode 3524 BN?",
  "Welke school staat op Kerkstraat 5 in Ede?",
  "Hoeveel verkeersongevallen waren er op de Ringweg 1 in Amsterdam?",
  "Welk waterschap gaat over postcode 3524 BN?",
  "Wat is de bodemkwaliteit op Kanaalweg 1 in Utrecht?",
  "Welke regels gelden voor kinderopvang op Kerkstraat 10 in Haarlem?",
  "Welke regels gelden voor horeca op de Grote Markt 1 in Groningen?",
  "Welke regels gelden voor de verkoop van Kerkstraat 10 in Haarlem?",
  "Mag ik mijn auto parkeren op Kerkstraat 10 in Ede?",
  "Mag ik vuurwerk afsteken op de Grote Markt 1 in Groningen?",
  "Mag ik een hond houden op Oudegracht 245 in Utrecht?",
  "Welke regels gelden voor de verhuur van Brennerbaan 150 in Utrecht?",
  "Wat is het bestemmingsplan van Brennerbaan 150 in Utrecht?",
  "Wanneer wordt het afval opgehaald op Kerkstraat 10 in Haarlem?",
  "Welke regels gelden voor thuiswerken op het Binnenhof 1 in Den Haag?",
  "Hoeveel inwoners heeft de gemeente met de omgevingsvisie van Amersfoort?",
  "Welke regels gelden er voor de Marathon 2026 op de Coolsingel in Rotterdam?",
  "Welke regels gelden voor de bouw van een school op Kerkstraat 10 in Ede?",
  "Welke Kamerleden stelden vragen over voorbereidingsbesluiten?",
  "Welke algoritmes gebruikt de gemeente Utrecht voor het omgevingsplan?",
  "Welke software gebruikt Amersfoort voor het omgevingsplan?",
  "Storing in het DSO bij het publiceren van omgevingsplannen",
  "Opleiding omgevingsrecht en omgevingsplannen in Utrecht",
  "Stand van zaken omgevingsvisie Groningen",
  "Wat doet de omgevingsdienst met het omgevingsplan van Ede?",
  "Wat zegt de VNG over voorbereidingsbesluiten?",
  "Wat zegt de gemeente Utrecht over het omgevingsplan?",
  "Hoe staat het met de omgevingsvisie van Zwolle?",
  "Welke regels gelden voor Rijksmonument 518 in Utrecht?",
  "Welke regels gelden voor Categorie 4 inrichtingen in Ede?",
  "Welke regels gelden voor de A2 bij knooppunt Oudenrijn 3?",
  "Welke regels gelden op Schiphol Terminal 2 voor drones?",
  "Welke regels gelden voor bodemsanering op postcode 3511 AB?",
  "Welke regels gelden voor deelscooters op Neude 11 in Utrecht?",
  "Welke regels gelden voor reclame op de gevel van Kerkstraat 10 in Haarlem volgens de APV?",
];

/** Questions the DSO answers: with the key they plan dso_omgevingsdocumenten. */
const DSO_QUESTIONS = [
  // The demo.
  "Welke omgevingsdocumenten gelden er op Brennerbaan 150 in Utrecht?",
  "Welke omgevingsdocumenten heeft de gemeente Utrecht?",
  "Wat is de omgevingsvisie van de provincie Utrecht?",
  "Welke ontwerp-omgevingsvisies liggen er ter inzage?",
  "Welke ontwerpen van omgevingsplannen liggen er ter inzage in de provincie Utrecht?",
  "Welke omgevingsdocumenten heeft Den Bosch?",
  "Welke omgevingsdocumenten golden er op 1 januari 2025 op Brennerbaan 150, en wat is er sindsdien bijgekomen?",
  // A document word with a place, a body or an area.
  "Omgevingsplan Utrecht",
  "Omgevingsvisie Rotterdam",
  "Omgevingsplan utrecht",
  "Wat is het omgevingsplan voor Utrecht?",
  "What does the omgevingsplan of Utrecht say about dormers?",
  "Voorbereidingsbesluit Utrecht dakkapellen",
  "Welke voorbereidingsbesluiten heeft Utrecht genomen?",
  "Wat zegt het omgevingsplan van Utrecht over dakkapellen?",
  "Wat zegt het omgevingsplan van Utrecht over woningen?",
  "Welke regelingen staan in het omgevingsplan van Amersfoort?",
  "Wat is het beleid in de omgevingsvisie van de provincie Utrecht?",
  "Mag ik een beroep aan huis uitoefenen volgens het omgevingsplan van Utrecht?",
  "Welke omgevingsplannen liggen er in Noord-Holland?",
  "Welke waterschapsverordening geldt in Utrecht?",
  "Wat staat er in de NOVI over woningbouw?",
  "Wat is de Nationale Omgevingsvisie?",
  // A list, the newest, ontwerpen.
  "Wat zijn de nieuwste omgevingsplannen?",
  "Wat zijn de nieuwste omgevingsdocumenten?",
  "Hoeveel omgevingsplannen zijn er in Nederland?",
  "Welke projectbesluiten zijn er?",
  "Welke ontwerpregelingen liggen er ter inzage?",
  "Welke ontwerp-omgevingsplannen liggen er nu ter inzage?",
  "Welke ontwerpen liggen ter inzage in de provincie Utrecht?",
  "Welke ontwerpen liggen er ter inzage bij de gemeente Zwolle?",
  "Welke omgevingsdocumenten van de provincie Utrecht liggen nu ter inzage?",
  // The rules at an address.
  "Welke regels gelden er op Brennerbaan 150 in Utrecht onder de Omgevingswet?",
  "Welke regels gelden op Brennerbaan 150 in Utrecht?",
  "Welke regels gelden op Oudegracht 245, Utrecht?",
  "Welke regels gelden op Kerkstraat 10 te Haarlem?",
  "Welke regels gelden op Kerkstraat 10 (Haarlem)?",
  "Regels voor Oudegracht 245 Utrecht",
  "Wat zijn de omgevingsregels voor Brennerbaan 150 in Utrecht?",
  "Wat mag ik bouwen op Brennerbaan 150 in Utrecht?",
  "Mag ik een dakkapel plaatsen op Oudegracht 100, Utrecht?",
  "Welke regels gelden er op Burgemeester Reigerstraat 10 in Utrecht?",
  "Welke regels gelden op 3524 BN 150?",
  "Welke omgevingsdocumenten gelden voor Neude 11, Utrecht?",
  "Welke omgevingsdocumenten golden er op 1 januari 2025 op Brennerbaan 150 in Utrecht?",
];

/**
 * DSO questions left to the routes they had, on purpose: no document word and
 * no street with a street ending or postcode, ontwerpen of no named body or
 * place, or a word another route owns (procedure, costs, permits).
 */
const LEFT_TO_OTHER_ROUTES = [
  "Welke regels gelden onder de Omgevingswet in Utrecht?",
  "Welke regels gelden onder de Omgevingswet voor Damrak 1 in Amsterdam?",
  "Welke regels gelden op Damrak 1 in Amsterdam?",
  "Welke regels gelden er op Lange Voorhout 9 in Den Haag?",
  "Which zoning rules apply at Damrak 1 Amsterdam?",
  "Wat zijn de regels voor een dakkapel in Utrecht?",
  "Mag ik een schuur bouwen in mijn achtertuin in Amersfoort?",
  "Welke regels gelden er in Amsterdam?",
  "Welke regels heeft de provincie Utrecht voor windturbines?",
  "Welke ontwerpen liggen er nu ter inzage?",
  "Wat ligt er ter inzage in Utrecht?",
  "Wat zijn de nieuwste ontwerpen in het DSO?",
  "Welke ontwerpbesluiten liggen nu ter inzage in Amsterdam?",
  "Zienswijze indienen op het ontwerp omgevingsplan van Amersfoort",
  "Wat zegt het omgevingsplan van Utrecht over kosten van parkeervergunningen?",
  "Kapvergunning regels in het omgevingsplan van Utrecht",
  "Welke programma's heeft de provincie Utrecht?",
  "Keur van het Hoogheemraadschap van Rijnland",
  "Welke regels uit de bruidsschat gelden in Utrecht?",
  "Omgevingsplan Nederland",
  "Omgevingsplan regels voor dakkapellen",
  "Wat zegt het omgevingsplan over dakkapellen?",
];

const ROUND_TWO = Object.entries(ROUND_TWO_NON_DSO).flatMap(([route, questions]) => questions.map((q) => [route, q] as const));
const ADVERSARIAL = ADVERSARIAL_NON_DSO.map((q) => ["adversarial", q] as const);

/** With DSO_API_KEY set, each question gets the plan it gets without the key. */
async function expectSamePlans(questions: ReadonlyArray<readonly [string, string]>) {
  for (const [route, question] of questions) {
    vi.stubEnv("DSO_API_KEY", "");
    const without = await plan(question);
    vi.stubEnv("DSO_API_KEY", "test-key");
    const withKey = await plan(question);
    expect(withKey, `${route}: ${question}`).toEqual(without);
    expect(withKey.estimated_sources, `${route}: ${question}`).not.toContain("dso_omgevingsdocumenten");
  }
}

describe("nl_gov_ask: questions for other routes keep their plan with DSO_API_KEY", () => {
  afterEach(() => {
    vi.unstubAllEnvs();
  });

  const all = Object.entries(NON_DSO_QUESTIONS).flatMap(([route, questions]) => questions.map((q) => [route, q] as const));

  it("holds corpora over every route: the first round's, the second round's and the adversarial set", () => {
    expect(all.length).toBeGreaterThanOrEqual(150);
    expect(new Set(all.map(([, q]) => q)).size).toBe(all.length);
    expect(ROUND_TWO.length).toBeGreaterThanOrEqual(400);
    expect(new Set(ROUND_TWO.map(([, q]) => q)).size).toBe(ROUND_TWO.length);
    expect(ADVERSARIAL.length).toBeGreaterThanOrEqual(100);
    expect(new Set(ADVERSARIAL_NON_DSO).size).toBe(ADVERSARIAL.length);
  });

  it("finds no DSO intent in them", () => {
    for (const [route, question] of [...all, ...ROUND_TWO, ...ADVERSARIAL]) expect(detectDsoIntent(question), `${route}: ${question}`).toBeUndefined();
  });

  it("plans exactly as without the key: first round", async () => {
    await expectSamePlans(all);
  });

  it("plans exactly as without the key: second round", { timeout: 60_000 }, async () => {
    await expectSamePlans(ROUND_TWO);
  });

  it("plans exactly as without the key: adversarial set", { timeout: 60_000 }, async () => {
    await expectSamePlans(ADVERSARIAL);
  });

  it("still plans the DSO for Omgevingswet document questions", async () => {
    vi.stubEnv("DSO_API_KEY", "test-key");
    for (const question of DSO_QUESTIONS) {
      expect((await plan(question)).estimated_sources, question).toEqual(["dso_omgevingsdocumenten"]);
    }
  });

  it("leaves the DSO questions it cannot read precisely to the routes they had", async () => {
    for (const question of LEFT_TO_OTHER_ROUTES) {
      expect(detectDsoIntent(question), question).toBeUndefined();
      vi.stubEnv("DSO_API_KEY", "");
      const without = await plan(question);
      vi.stubEnv("DSO_API_KEY", "test-key");
      expect(await plan(question), question).toEqual(without);
    }
  });
});
